public class Testing {
    public String names {get;set;}
    public integer age {get;set;}
    public Map<String, String> mapExample {get;set;}
    
    
   public Testing(){ 
       names = 'Luis';
       mapExample = new Map<String, String> ();
       CalculateAge();
    }
    
    
    Testing( string x ){}
    public void CalculateAge(){
	    AGE = 2020 - 1995;
        mapExample.put('a', 'Luis map');
        mapExample.put('b', 'Gustavo map');
        mapExample.put('c', 'Shoba map');
        if(AGE == 25){
            System.debug(AGE); 
        } 
    }
    
    
}