public class testing2 {
    public String names {get;set;}
       public String lastName {get;set;}
    public integer age {get;set;}
    
    
   public testing2(){   
       names = '';
    }
    
    public  PAgereference updateAge(){
        age=4654;
        lastName='updatre age 1';
        return null;
    } 
    
        
    public  PAgereference updateAge2(){
        age=11111;
        lastName='updatre age 2';
        return null;
    }
    
    

    
}